stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
    - data/housing.csv
    - src/preprocessing.py
    outs:
    - data/housing_processed.csv
  training:
    cmd: python src/training.py
    deps:
    - data/housing_processed.csv
    - src/training.py
    outs:
    - model/model.pkl
