[project]
name = "dvc-test"
version = "0.1.0"
description = "first interaction with dvc"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc>=3.59.1",
    "mlflow>=2.21.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
